# Generated by Django 5.2.6 on 2025-09-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pararead_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingmaterial',
            name='simplified_segments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='readingmaterial',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
