# Generated by Django 5.2.6 on 2025-09-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pararead_app', '0002_readingmaterial_simplified_segments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingmaterial',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
